language: go
go_import_path: gopkg.in/oauth2.v3

env:
  - GO111MODULE=on

go:
  - 1.12.x
  - 1.13.x

before_install:
  - go mod download

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
